/**
 * The Forge mark in VS Code's own chrome.
 *
 * Reported from a real install: "the title-bar/activity-bar icon was empty".
 * Every surface now carries the one mark, the F with the cube in its niche.
 *
 * VS Code draws the two surfaces differently, and that is the whole bug:
 *
 *   - a `viewsContainers` icon is *masked* to the theme foreground, so only
 *     the alpha channel survives and `fill="currentColor"` is correct;
 *   - a `contributes.commands[].icon` and a `WebviewPanel.iconPath` are drawn
 *     as images, colours and all. In an isolated SVG document `currentColor`
 *     resolves to the initial value of `color`, which is black -- invisible on
 *     a dark theme. The official ships a literal `#D97757` for exactly these
 *     two, and passes the one file as both `light` and `dark`.
 */
import { describe, expect, it } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { inflateSync } from 'node:zlib';
import { join } from 'node:path';
import { F_CUBE, F_SOLID } from '../src/webview/src/components/forge/marks';
import { REST_YAW, toView } from '../src/webview/src/components/forge/cube';

const ROOT = join(__dirname, '..');
const read = (rel: string) => readFileSync(join(ROOT, rel), 'utf8');

const manifest = JSON.parse(read('package.json')) as any;
const maskedCut = read('resources/forge-logo.svg');
const brandCut = read('resources/forge-logo-brand.svg');

/**
 * Every mark Forge ships to VS Code, generated or not.
 *
 * This is the check that would have caught the reported defect. SVG is XML, and
 * XML forbids `--` inside a comment; both generator scripts emitted
 * `<!-- GENERATED by … -- do not edit by hand. -->`, so every file they wrote
 * was unparseable. Rendered in a browser they came out as broken-image
 * placeholders, and masked as an activity-bar icon they came out as nothing at
 * all. "The icon was empty" was literally true.
 */
describe('every shipped SVG is well-formed XML', () => {
  const files = readdirSync(join(ROOT, 'resources')).filter((f) => f.endsWith('.svg'));

  it('there are marks to check', () => {
    expect(files.length).toBeGreaterThan(0);
  });

  it.each(files)('%s has no "--" inside a comment', (file) => {
    const svg = read(join('resources', file));
    for (const [, body] of svg.matchAll(/<!--([\s\S]*?)-->/g)) {
      expect(body).not.toContain('--');
    }
  });

  it.each(files)('%s opens and closes an <svg> element', (file) => {
    const svg = read(join('resources', file));
    expect(svg).toMatch(/<svg[\s>]/);
    expect(svg).toContain('</svg>');
    expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"');
  });

  it.each(files)('%s has balanced angle brackets', (file) => {
    const svg = read(join('resources', file));
    expect((svg.match(/</g) ?? []).length).toBe((svg.match(/>/g) ?? []).length);
  });
});

describe('the mark: the F with the cube in its crossbar niche', () => {
  it('the F is the stem and the top bar, no crossbar', () => {
    expect(F_SOLID).toEqual([[0, 0, 2, 6], [2, 0, 4, 2]]);
  });

  it("the cube is cube.ts's finished cube, seen from the same angle", () => {
    // Project a cube of half-size 1 exactly as cube.ts does, fit it to the
    // niche the same way (width 3, left edge 2.5, top apex 2.4), and compare.
    const project = ([x, y, z]: [number, number, number]) => {
      const [vx, vy] = toView([x, y, z], REST_YAW);
      return [vx, -vy];
    };
    const corners = {
      top: [[-1, 1, -1], [1, 1, -1], [1, 1, 1], [-1, 1, 1]],
      lit: [[-1, 1, 1], [1, 1, 1], [1, -1, 1], [-1, -1, 1]],
    } as const;
    const all = [...corners.top, ...corners.lit].map((c) => project(c as [number, number, number]));
    const minX = Math.min(...all.map((p) => p[0]));
    const maxX = Math.max(...all.map((p) => p[0]));
    const minY = Math.min(...all.map((p) => p[1]));
    const k = 3 / (maxX - minX);
    const place = (c: readonly number[]) => {
      const [x, y] = project(c as [number, number, number]);
      return [2.5 + (x - minX) * k, 2.4 + (y - minY) * k];
    };
    const expectFace = (face: ReadonlyArray<readonly [number, number]>, expected: number[][]) => {
      // Same points, any starting corner.
      for (const point of expected) {
        expect(face.some(([x, y]) => Math.abs(x - point[0]) < 0.002 && Math.abs(y - point[1]) < 0.002)).toBe(true);
      }
    };
    expectFace(F_CUBE.top, corners.top.map(place));
    // The lit face turns toward the light at the upper left: it is the left side.
    const litX = Math.max(...F_CUBE.lit.map(([x]) => x));
    const shadeX = Math.min(...F_CUBE.shade.map(([x]) => x));
    expect(litX).toBeCloseTo(4, 3);
    expect(shadeX).toBeCloseTo(4, 3);
    // Every drawn corner is a visible corner of the projected cube, and back.
    const visible = [-1, 1]
      .flatMap((x) => [-1, 1].flatMap((y) => [-1, 1].map((z) => [x, y, z])))
      .sort((p, q) => toView(p as [number, number, number], REST_YAW)[2] - toView(q as [number, number, number], REST_YAW)[2])
      .slice(1) // the far corner is hidden
      .map(place);
    const drawn = [...F_CUBE.top, ...F_CUBE.lit, ...F_CUBE.shade];
    for (const [x, y] of drawn) {
      expect(visible.some((p) => Math.abs(p[0] - x) < 0.002 && Math.abs(p[1] - y) < 0.002)).toBe(true);
    }
    for (const p of visible) {
      expect(drawn.some(([x, y]) => Math.abs(p[0] - x) < 0.002 && Math.abs(p[1] - y) < 0.002)).toBe(true);
    }
  });

  it('the cube sits in the niche, clear of the stem and the top bar', () => {
    const points = [...F_CUBE.top, ...F_CUBE.lit, ...F_CUBE.shade];
    expect(Math.min(...points.map(([x]) => x))).toBeGreaterThan(2);
    expect(Math.min(...points.map(([, y]) => y))).toBeGreaterThan(2);
    expect(Math.max(...points.map(([x]) => x))).toBeLessThanOrEqual(6);
    expect(Math.max(...points.map(([, y]) => y))).toBeLessThanOrEqual(6);
  });

  it('the masked cut is currentColor only, the faces told apart by opacity', () => {
    expect(maskedCut).toContain('fill="currentColor"');
    expect(maskedCut).not.toMatch(/fill="#/);
    expect(maskedCut).toContain('opacity="1"');
    expect(maskedCut).toContain('opacity="0.6"');
    expect(maskedCut).toContain('opacity="0.3"');
  });

  it('the brand cut names its colours, so it survives being drawn as an image', () => {
    expect(brandCut).not.toContain('currentColor');
    const fills = [...brandCut.matchAll(/fill="(#[0-9a-fA-F]{6})"/g)].map((m) => m[1]);
    // The F and three distinct faces.
    expect(new Set(fills).size).toBe(4);
  });

  it('both cuts carry the F and the three faces', () => {
    for (const svg of [maskedCut, brandCut]) {
      expect((svg.match(/<rect /g) ?? []).length).toBe(2);
      expect((svg.match(/<path /g) ?? []).length).toBe(3);
    }
  });

  it('the brand colours are the --forge-mark-* tokens the webview paints', () => {
    const palette = read('src/webview/src/styles/forge-pajamas.css');
    const tokens = read('src/webview/src/styles/forge-tokens.css');
    const hex = (token: string) => {
      const stop = tokens.match(new RegExp(`${token}:\\s*var\\(--pajamas-([a-z0-9-]+)\\)`))?.[1];
      return palette.match(new RegExp(`--pajamas-${stop}:\\s*(#[0-9a-fA-F]{6})`))?.[1]?.toLowerCase();
    };
    for (const token of ['--forge-mark-f', '--forge-mark-cube-top', '--forge-mark-cube-lit', '--forge-mark-cube-shade']) {
      expect(brandCut).toContain(`fill="${hex(token)}"`);
    }
  });
});

describe('each surface gets the cut it can render', () => {
  it('the editor title button uses the brand cut', () => {
    const command = manifest.contributes.commands.find(
      (c: any) => c.command === 'forge.editor.openLast',
    );
    expect(command.icon).toBe('resources/forge-logo-brand.svg');
  });

  it('every view container uses the masked cut', () => {
    const containers = [
      ...manifest.contributes.viewsContainers.activitybar,
      ...manifest.contributes.viewsContainers.secondarySidebar,
    ];
    expect(containers.length).toBeGreaterThan(0);
    for (const container of containers) {
      expect(container.icon).toBe('resources/forge-logo.svg');
    }
  });

  it('no command icon points at the masked cut', () => {
    // A `currentColor` SVG on a command is the defect, in whichever command it
    // appears next.
    for (const command of manifest.contributes.commands) {
      expect(command.icon).not.toBe('resources/forge-logo.svg');
    }
  });

  it('both cuts ship in the VSIX', () => {
    const ignored = read('.vscodeignore').split(/\r?\n/).map((l) => l.trim());
    expect(ignored).not.toContain('resources/**');
    expect(ignored).not.toContain('resources');
  });
});

describe('the Marketplace icon', () => {
  const png = readFileSync(join(ROOT, 'resources/forge-logo.png'));
  const width = png.readUInt32BE(16);
  const idat: Buffer[] = [];
  for (let i = 8; i < png.length; ) {
    const n = png.readUInt32BE(i);
    if (png.toString('ascii', i + 4, i + 8) === 'IDAT') idat.push(png.subarray(i + 8, i + 8 + n));
    i += 12 + n;
  }
  const pixels = inflateSync(Buffer.concat(idat));
  const alpha = (x: number, y: number) => pixels[y * (width * 4 + 1) + 1 + x * 4 + 3];

  it('is the manifest icon, 256px square RGBA', () => {
    expect(manifest.icon).toBe('resources/forge-logo.png');
    expect(width).toBe(256);
    expect(png.readUInt32BE(20)).toBe(256);
    expect(png[25]).toBe(6); // colour type RGBA
  });

  it('has a transparent background around the mark', () => {
    for (const [x, y] of [[0, 0], [255, 0], [0, 255], [255, 255], [128, 5], [250, 128]]) {
      expect(alpha(x, y)).toBe(0);
    }
    // The F's stem and the cube's centre are opaque.
    expect(alpha(40, 128)).toBe(255);
    expect(alpha(20 + 4 * 36, 20 + 4 * 36)).toBe(255);
  });
});

describe('the terminal tab carries the brand cut', () => {
  it('points the terminal icon at a file with its colours baked in', () => {
    const handlers = read('src/services/claude/handlers/handlers.ts');
    expect(handlers).toContain('path.join("resources", "forge-logo-brand.svg")))');
    expect(handlers).not.toContain('path.join("resources", "forge-logo.svg")');
  });
});

describe('the editor tab carries the mark', () => {
  const service = read('src/services/webViewService.ts');

  it('sets iconPath on the page panel', () => {
    // Without this the tab shows VS Code's generic webview glyph, which is
    // what "opens like a coding file window" looked like.
    expect(service).toContain('panel.iconPath = this.panelIcon()');
  });

  it('points that icon at the brand cut', () => {
    expect(service).toContain("'forge-logo-brand.svg'");
  });

  it('passes one file as both light and dark, like the official', () => {
    expect(service).toMatch(/light:\s*uri,\s*dark:\s*uri/);
  });
});
