/**
 * The Forge mark in VS Code's own chrome.
 *
 * Reported from a real install: "the title-bar/activity-bar icon was empty,
 * not the voxel cube on the welcome page."
 *
 * VS Code draws the two surfaces differently, and that is the whole bug:
 *
 *   - a `viewsContainers` icon is *masked* to the theme foreground, so only
 *     the alpha channel survives and `fill="currentColor"` is correct;
 *   - a `contributes.commands[].icon` and a `WebviewPanel.iconPath` are drawn
 *     as images, colours and all. In an isolated SVG document `currentColor`
 *     resolves to the initial value of `color`, which is black -- invisible on
 *     a dark theme. The official ships a literal `#D97757` for exactly these
 *     two, and passes the one file as both `light` and `dark`.
 */
import { describe, expect, it } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(__dirname, '..');
const read = (rel: string) => readFileSync(join(ROOT, rel), 'utf8');

const manifest = JSON.parse(read('package.json')) as any;
const maskedCut = read('resources/forge-cube.svg');
const brandCut = read('resources/forge-cube-brand.svg');

/**
 * Every mark Forge ships to VS Code, generated or not.
 *
 * This is the check that would have caught the reported defect. SVG is XML, and
 * XML forbids `--` inside a comment; both generator scripts emitted
 * `<!-- GENERATED by … -- do not edit by hand. -->`, so every file they wrote
 * was unparseable. Rendered in a browser they came out as broken-image
 * placeholders, and masked as an activity-bar icon they came out as nothing at
 * all. "The icon was empty" was literally true.
 */
describe('every shipped SVG is well-formed XML', () => {
  const files = readdirSync(join(ROOT, 'resources')).filter((f) => f.endsWith('.svg'));

  it('there are marks to check', () => {
    expect(files.length).toBeGreaterThan(0);
  });

  it.each(files)('%s has no "--" inside a comment', (file) => {
    const svg = read(join('resources', file));
    for (const [, body] of svg.matchAll(/<!--([\s\S]*?)-->/g)) {
      expect(body).not.toContain('--');
    }
  });

  it.each(files)('%s opens and closes an <svg> element', (file) => {
    const svg = read(join('resources', file));
    expect(svg).toMatch(/<svg[\s>]/);
    expect(svg).toContain('</svg>');
    expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"');
  });

  it.each(files)('%s has balanced angle brackets', (file) => {
    const svg = read(join('resources', file));
    expect((svg.match(/</g) ?? []).length).toBe((svg.match(/>/g) ?? []).length);
  });
});

describe('the two cuts of the cube', () => {
  it('the masked cut is a single currentColor shape', () => {
    expect(maskedCut).toContain('fill="currentColor"');
    expect(maskedCut).not.toMatch(/fill="#/);
  });

  it('the brand cut names its colours, so it survives being drawn as an image', () => {
    expect(brandCut).not.toContain('currentColor');
    expect(brandCut).toMatch(/fill="#[0-9a-fA-F]{6}"/);
  });

  it('both are real geometry, not an empty frame', () => {
    for (const svg of [maskedCut, brandCut]) {
      expect(svg).toContain('<svg');
      expect(svg).toMatch(/viewBox="[-\d. ]+"/);
      expect((svg.match(/<path /g) ?? []).length).toBeGreaterThan(10);
    }
  });

  it('is the voxel cut the welcome page draws, not a generic solid cube', () => {
    // `ForgeWordmark.vue` renders `markPaths(0.35)`; the chrome icons render
    // the same roughness, so the mark in VS Code's own furniture is the mark
    // people recognise from the welcome page. A solid three-face cube reads
    // crisper at 16px and is not Forge's.
    const generator = read('scripts/gen-cube-icon.ts');
    expect(generator).toContain('const ROUGHNESS = 0.35');

    const wordmark = read('src/webview/src/components/ForgeWordmark.vue');
    const drawn = wordmark.match(/markPaths\(([\d.]+)\)/)?.[1];
    expect(drawn).toBe('0.35');

    // Many small faces, which is what makes it the voxel cube.
    for (const svg of [maskedCut, brandCut]) {
      expect((svg.match(/<path /g) ?? []).length).toBeGreaterThan(50);
    }
  });

  it('separates the three faces by opacity, so a mask still reads as a cube', () => {
    expect(maskedCut).toContain('opacity="1"');
    expect(maskedCut).toContain('opacity="0.58"');
    expect(maskedCut).toContain('opacity="0.26"');
  });
});

describe('each surface gets the cut it can render', () => {
  it('the editor title button uses the brand cut', () => {
    const command = manifest.contributes.commands.find(
      (c: any) => c.command === 'forge.editor.openLast',
    );
    expect(command.icon).toBe('resources/forge-cube-brand.svg');
  });

  it('every view container uses the masked cut', () => {
    const containers = [
      ...manifest.contributes.viewsContainers.activitybar,
      ...manifest.contributes.viewsContainers.secondarySidebar,
    ];
    expect(containers.length).toBeGreaterThan(0);
    for (const container of containers) {
      expect(container.icon).toBe('resources/forge-cube.svg');
    }
  });

  it('no command icon points at the masked cut', () => {
    // A `currentColor` SVG on a command is the defect, in whichever command it
    // appears next.
    for (const command of manifest.contributes.commands) {
      expect(command.icon).not.toBe('resources/forge-cube.svg');
    }
  });

  it('both cuts ship in the VSIX', () => {
    const ignored = read('.vscodeignore').split(/\r?\n/).map((l) => l.trim());
    expect(ignored).not.toContain('resources/**');
    expect(ignored).not.toContain('resources');
  });
});

describe('the editor tab carries the mark', () => {
  const service = read('src/services/webViewService.ts');

  it('sets iconPath on the page panel', () => {
    // Without this the tab shows VS Code's generic webview glyph, which is
    // what "opens like a coding file window" looked like.
    expect(service).toContain('panel.iconPath = this.panelIcon()');
  });

  it('points that icon at the brand cut', () => {
    expect(service).toContain("'forge-cube-brand.svg'");
  });

  it('passes one file as both light and dark, like the official', () => {
    expect(service).toMatch(/light:\s*uri,\s*dark:\s*uri/);
  });
});
