/**
 * Emit the Forge cube as static SVG files for VS Code's own surfaces.
 *
 * The cube in the webview is drawn by `components/forge/cube.ts`, but
 * `package.json` contributions cannot run a Vue component -- the activity bar
 * and the editor title bar need files on disk. This generates them from the
 * same geometry, so the mark in VS Code's chrome and the mark inside the
 * webview cannot drift apart.
 *
 * Two cuts, because VS Code renders its surfaces two different ways:
 *
 *   forge-cube.svg        one `currentColor` shape, for `viewsContainers`.
 *                         VS Code *masks* those to the theme foreground, so
 *                         only alpha survives and the three faces are
 *                         separated by opacity instead of by hue.
 *   forge-cube-brand.svg  the faces in Pajamas purple, for a
 *                         `contributes.commands[].icon` and a
 *                         `WebviewPanel.iconPath`. Those are drawn as images,
 *                         colours kept -- and in an isolated SVG document
 *                         `currentColor` resolves to black, which is invisible
 *                         on a dark theme. The official ships a literal
 *                         `#D97757` for exactly these two.
 *
 * Usage: pnpm exec tsx scripts/gen-cube-icon.ts
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { markPaths, type Ink } from '../src/webview/src/components/forge/cube';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Opacity per face, so a single-colour icon still reads as a cube.
 *
 * Spread wider than the wordmark's own tones because VS Code tints this to one
 * colour at 16-24px, where a narrow spread turns the mark into a blob.
 * Measured at 16px against the solid geometry below, the three faces stay
 * separable at this spread.
 */
const FLAT: Record<Ink, number> = { top: 1, lit: 0.58, shade: 0.26 };
/** Pajamas purple, as the brand mark uses it. */
const BRAND: Record<Ink, string> = { top: '#9d7ee0', lit: '#7759c2', shade: '#5b4499' };

/**
 * The voxel cut, the same `0.35` `ForgeWordmark.vue` draws on the welcome page.
 *
 * Asked for by name: the mark in VS Code's chrome should be *the* Forge mark,
 * the cube mid-forge, not a generic solid one. So the activity-bar container,
 * the `editor/title` button and the webview tab all carry it.
 *
 * It is a real trade. Rendered and compared at 16 / 20 / 24 / 32px, the voxel
 * gaps are sub-pixel below about 24px, so the mark reads as texture rather than
 * as three clean faces -- `markPaths(0)` stays crisper there. Brand identity
 * won, which is the right call to be the user's: a mark nobody recognises is
 * worse than one that is slightly soft. `PADDING` and the opacity spread below
 * are set to give this cut the best chance at those sizes.
 */
const ROUGHNESS = 0.35;

function render(size: number, paint: (ink: Ink) => string): string {
  const { paths, box } = markPaths(ROUGHNESS);
  const [bx, by, bw, bh] = box;
  // A little air, so the mark is not flush against the icon's edge.
  const pad = Math.max(bw, bh) * 0.08;
  const view = [bx - pad, by - pad, bw + pad * 2, bh + pad * 2]
    .map((n) => n.toFixed(3)).join(' ');
  const body = paths.map((p) => `  <path d="${p.d}" ${paint(p.ink)}/>`).join('\n');

  // No `--` inside the comment: SVG is XML, and XML forbids a double hyphen in
  // a comment. The earlier banner carried one, which made every icon this
  // script writes unparseable -- browsers drew a broken-image placeholder and
  // VS Code drew nothing at all. That is why the mark in the chrome was empty.
  return `<!-- GENERATED by scripts/gen-cube-icon.ts. Do not edit by hand. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${view}" width="${size}" height="${size}">
${body}
</svg>
`;
}

writeFileSync(
  join(ROOT, 'resources/forge-cube.svg'),
  render(24, (ink) => `fill="currentColor" opacity="${FLAT[ink]}"`),
  'utf8',
);
writeFileSync(
  join(ROOT, 'resources/forge-cube-brand.svg'),
  render(24, (ink) => `fill="${BRAND[ink]}"`),
  'utf8',
);
console.log('gen-cube-icon: wrote resources/forge-cube.svg and resources/forge-cube-brand.svg');
